x-veld:
  code:
    about:
      description: "prints information about the python intepreter within the docker container."
      topic: "testing"

services:
  veld:
    build: .
    volumes:
      - ./test.py:/veld/code/test.py
    command: python /veld/code/test.py

